Add Support for Oasis v23
SimplyStaking/oasis_api_server pull request #13
Opened 2023-12-01 04:03 UTC by keefertaylor

This PR updates dependencies and types for Oasis v23, released earlier this week.

2023-12-02 12:26 UTC, VitalyVolozhinov requested changes
Remove comment and LGTM

2023-12-02 12:36 UTC, VitalyVolozhinov commented on src/handlers/registry_handler.go
> +	// query := registry.NamespaceQuery{Height: height, ID: nameSpace}
```suggestion
```

2024-01-04 03:32 UTC, keefertaylor commented
Hey @VitalyVolozhinov - so sorry for not getting back to you. I missed your comment with the holidays. 

Should be good to go now.

2024-01-12 09:06 UTC, merged

2024-01-12 09:06 UTC, VitalyV1337 commented
Thank you @keefertaylor